//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutlassShare.Protocall {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Token {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Token() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CutlassShare.Protocall.Token", typeof(Token).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamestart.
        /// </summary>
        public static string GameStart {
            get {
                return ResourceManager.GetString("GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give.
        /// </summary>
        public static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $$.
        /// </summary>
        public static string Splitter {
            get {
                return ResourceManager.GetString("Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turnstart.
        /// </summary>
        public static string TurnStart {
            get {
                return ResourceManager.GetString("TurnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
    }
}
